// Generated by CoffeeScript 1.3.3

goog.provide('app.Alerter');

app.Alerter = (function() {

  function Alerter() {}

  Alerter.prototype.alert = function(arg) {
    return alert(arg);
  };

  return Alerter;

})();
