// Generated by CoffeeScript 1.3.3

goog.provide('app.ConsoleLogger');

app.ConsoleLogger = (function() {

  function ConsoleLogger() {}

  ConsoleLogger.prototype.log = function(args) {
    return console.log(args);
  };

  return ConsoleLogger;

})();
