// Generated by CoffeeScript 1.3.3

goog.provide('app.Messenger');

app.Messenger = (function() {

  function Messenger(consoleLogger, alerter) {
    this.consoleLogger = consoleLogger;
    this.alerter = alerter;
  }

  Messenger.prototype.show = function(type, message) {
    this.consoleLogger.log(type + ': ' + message);
    return this.alerter.alert(type + ': ' + message);
  };

  Messenger.prototype.showError = function(message) {
    return this.show('error', message);
  };

  return Messenger;

})();
