// Generated by CoffeeScript 1.3.3

goog.provide('app.start');

goog.require('app.di.Container.build');

app.start = (function() {

  function start() {
    var messenger;
    this.container = app.di.Container.build();
    messenger = this.container.get('messenger');
    messenger.showError('Yes');
  }

  return start;

})();

new app.start;
