// Generated by CoffeeScript 1.3.3

goog.provide('app.start');

goog.require('dependencyInjection.Container.get');

app.start = (function() {

  function start() {
    var messenger;
    this.container = dependencyInjection.Container.get();
    messenger = this.container.get('messenger');
    messenger.showError('Yes');
  }

  return start;

})();

new app.start;
